version: "3.7"
services:
  #Laravel app
  appblog:
    build:
      args:
        user: mt
        uid: 501
      context: ./
      dockerfile: Dockerfile
    image: blog
    container_name: blog-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - blog
  nginxblog:
    image: nginx:1.17-alpine
    container_name: blog-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - blog
  dbblog:
    image: mysql:5.7
    container_name: blog-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - blog

networks:
  blog:
    driver: bridge